### ISSUE TITLE
Not able to connect to microstation

### ISSUE THREAD

**Issue by BigNom** [wieslawsoltes/MicroStationTagExplorer#2]
Hi
Can you please tell me how can I get this tool to work? I can see the dialog but there is not interaction with microstation.
Thanks

**Comment by wieslawsoltes** [comment]
That is known issue with Microstation Interop. Try opening some drawing in Microstation and then use the program.

**Comment by BigNom** [comment]
Oh okay I'll do some research on Microstation Interop and see if I can get this to run. I am using AECOsim Ss6 and visual studio 2017, could this be causing the issue? Do you mind telling me what I should be able to see when your project is up and running? I have added a dgn file and it appears in the Files tab but I'm not sure what is meant to happen.
